# Generated by Django 5.0.3 on 2025-06-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_movie_genre_movie_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="movie_images/"),
        ),
    ]
