# Generated by Django 5.0.3 on 2025-06-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_movie_duration_movie_theater"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
