# Generated by Django 5.0.3 on 2025-06-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_reservation_qr_code_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="show_time",
            field=models.CharField(default="未設定", max_length=50),
        ),
    ]
