# Generated by Django 5.0.3 on 2025-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="convenience_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
