# Generated by Django 5.0.3 on 2025-06-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_reservation_convenience_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "現金"),
                    ("credit_card", "クレジットカード"),
                    ("paypal", "PayPal"),
                    ("merpay", "メルペイ"),
                    ("paypay", "PayPay"),
                    ("convenience_store", "コンビニ払い"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="show_time",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("movie", "seat", "show_time")},
        ),
    ]
