# Generated by Django 5.0.3 on 2025-09-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_showschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
