# Generated by Django 5.0.3 on 2025-12-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_userprofile_is_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["status", "-show_date"]},
        ),
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(
                blank=True,
                help_text="公開予定日（coming_soonの場合に設定）",
                null=True,
                verbose_name="公開日",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[("now_showing", "上映中"), ("coming_soon", "公開予定")],
                default="now_showing",
                max_length=20,
                verbose_name="上映ステータス",
            ),
        ),
    ]
