# Generated by Django 4.2.16 on 2025-12-10 08:24

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0015_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="クーポンコード"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "パーセント割引"),
                            ("fixed", "定額割引"),
                            ("free", "無料"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="割引タイプ",
                    ),
                ),
                ("discount_value", models.IntegerField(verbose_name="割引値")),
                ("min_purchase", models.IntegerField(default=0, verbose_name="最小購入金額")),
                ("max_uses", models.IntegerField(default=1, verbose_name="最大使用回数")),
                ("used_count", models.IntegerField(default=0, verbose_name="使用回数")),
                ("start_date", models.DateTimeField(verbose_name="開始日時")),
                ("expiry_date", models.DateTimeField(verbose_name="終了日時")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "クーポン",
                "verbose_name_plural": "クーポン",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "チャットメッセージ",
                "verbose_name_plural": "チャットメッセージ",
            },
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["status", "-show_date"],
                "verbose_name": "映画",
                "verbose_name_plural": "映画",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-reserved_at"],
                "verbose_name": "予約",
                "verbose_name_plural": "予約",
            },
        ),
        migrations.AlterModelOptions(
            name="seat",
            options={"verbose_name": "座席", "verbose_name_plural": "座席"},
        ),
        migrations.AlterModelOptions(
            name="showschedule",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name": "上映スケジュール",
                "verbose_name_plural": "上映スケジュール",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "ユーザープロフィール", "verbose_name_plural": "ユーザープロフィール"},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="生年月日"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 12, 10, 8, 24, 29, 917724, tzinfo=datetime.timezone.utc
                ),
                verbose_name="作成日時",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="membership_level",
            field=models.CharField(
                choices=[
                    ("standard", "スタンダード"),
                    ("gold", "ゴールド"),
                    ("platinum", "プラチナ"),
                ],
                default="standard",
                max_length=20,
                verbose_name="会員レベル",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.IntegerField(default=0, verbose_name="ポイント"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="is_user",
            field=models.BooleanField(default=True, verbose_name="ユーザーメッセージ"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="convenience_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="コンビニ種類"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(verbose_name="説明"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="上映時間（分）", null=True, verbose_name="上映時間"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(blank=True, max_length=100, verbose_name="ジャンル"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="movie_images/", verbose_name="画像"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="支払い方法"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="料金",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="show_date",
            field=models.DateField(verbose_name="上映日"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="theater",
            field=models.CharField(
                blank=True,
                help_text="シアター名",
                max_length=100,
                null=True,
                verbose_name="シアター",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=200, verbose_name="タイトル"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="既読"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=255, verbose_name="メッセージ"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="convenience_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("7eleven", "セブンイレブン"),
                    ("famima", "ファミリーマート"),
                    ("daily", "デイリーヤマザキ"),
                    ("ministop", "ミニストップ"),
                    ("lawson", "ローソン"),
                ],
                max_length=20,
                null=True,
                verbose_name="コンビニ種類",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.movie",
                verbose_name="映画",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "現金"),
                    ("credit_card", "クレジットカード"),
                    ("paypal", "PayPal"),
                    ("merpay", "メルペイ"),
                    ("paypay", "PayPay"),
                    ("convenience_store", "コンビニ払い"),
                ],
                default="cash",
                max_length=20,
                verbose_name="支払い方法",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="qr_code_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="qr_codes/", verbose_name="QRコード"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserved_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="予約日時"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.seat",
                verbose_name="座席",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="show_time",
            field=models.CharField(max_length=50, verbose_name="上映時間"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_number",
            field=models.CharField(max_length=5, verbose_name="座席番号"),
        ),
        migrations.AlterField(
            model_name="showschedule",
            name="date",
            field=models.DateField(verbose_name="上映日"),
        ),
        migrations.AlterField(
            model_name="showschedule",
            name="end_time",
            field=models.TimeField(verbose_name="終了時間"),
        ),
        migrations.AlterField(
            model_name="showschedule",
            name="format",
            field=models.CharField(blank=True, max_length=50, verbose_name="上映形式"),
        ),
        migrations.AlterField(
            model_name="showschedule",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="pages.movie",
                verbose_name="映画",
            ),
        ),
        migrations.AlterField(
            model_name="showschedule",
            name="screen",
            field=models.IntegerField(verbose_name="スクリーン"),
        ),
        migrations.AlterField(
            model_name="showschedule",
            name="start_time",
            field=models.TimeField(verbose_name="開始時間"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="電話番号"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="プロフィール画像",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.CreateModel(
            name="PointHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="ポイント増減")),
                ("reason", models.CharField(max_length=200, verbose_name="理由")),
                ("balance_after", models.IntegerField(verbose_name="変更後残高")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ポイント履歴",
                "verbose_name_plural": "ポイント履歴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="使用日時"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="pages.coupon",
                        verbose_name="クーポン",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.reservation",
                        verbose_name="予約",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザークーポン",
                "verbose_name_plural": "ユーザークーポン",
                "ordering": ["-used_at"],
                "unique_together": {("user", "coupon")},
            },
        ),
    ]
