# Generated by Django 4.2.16 on 2025-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_coupon_alter_chatmessage_options_alter_movie_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="プロフィール完了"),
        ),
    ]
