# Generated by Django 4.2.16 on 2025-12-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_userprofile_is_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="お名前")),
                ("email", models.EmailField(max_length=254, verbose_name="メールアドレス")),
                ("message", models.TextField(verbose_name="お問い合わせ内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="送信日時"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="既読")),
            ],
            options={
                "verbose_name": "お問い合わせ",
                "verbose_name_plural": "お問い合わせ",
                "ordering": ["-created_at"],
            },
        ),
    ]
