# Generated by Django 4.2.16 on 2026-01-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("general", "一般"),
                            ("student", "大学生・専門学生"),
                            ("youth", "高校生以下"),
                            ("senior", "シニア（60歳以上）"),
                            ("disability", "障がい者割引"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="チケット種別",
                    ),
                ),
                ("price", models.IntegerField(default=1900, verbose_name="料金")),
                (
                    "ticket_number",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="チケット番号"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="発券日時"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="使用済み")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用日時"),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="pages.reservation",
                        verbose_name="予約",
                    ),
                ),
            ],
            options={
                "verbose_name": "チケット",
                "verbose_name_plural": "チケット",
                "ordering": ["-issued_at"],
            },
        ),
    ]
