# Generated by Django 4.2.16 on 2026-01-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_in_reservations",
                to="pages.coupon",
                verbose_name="適用クーポン",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="割引金額"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="最終支払金額"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="元の金額"
            ),
        ),
    ]
